### ISSUE TITLE
the presence of the statsd panel on django_toolbar seems to break the templates panel

### ISSUE THREAD

**Issue by Lacrymology** [django-statsd/django-statsd#15]
- My Templates panel on the django debug toolbar broke.
- I've done a git bisect and found that the breaking point is when I added the statsd panel.
- I've confirmed that removing the statsd panel fixes the problem. Just commenting out the line in `DEBUG_TOOLBAR_PANELS` without changing any other settings

I have latest versions of django, django-debug-toolbar and django-statsd-mozilla. I haven't created a minimal example yet to confirm this. Is this a known issue? are there any fixes?

**Comment by xordoquy** [comment]
Should be fixed by #17
