### ISSUE TITLE
Don't use .timing for statsd_ping

### ISSUE THREAD

**Issue by jsocol** [django-statsd/django-statsd#5]
The `statsd_ping` management command [currently uses](https://github.com/andymckay/django-statsd/blob/master/django_statsd/management/commands/statsd_ping.py#L23) `StatsClient.timing` to send non-timing data.

I admit that this isn't well documented, but the second argument to `StatsClient.timing` is an integer number of milliseconds, designed to time how long something took. (It's used internally by `StatsClient.timer`, for an example.) Currently we're passing a totally nonsensical value for this.

We should really be using `incr` to send a ping here. For our use case, the `drawAsInfinite` modifier should still work exactly the same way.

**Comment by xordoquy** [comment]
I'm closing this due to it's age. Will reopen upon updates.
