### ISSUE TITLE
Incorrect gauge signature, confusion with required statsd version

### ISSUE THREAD

**Issue by smant** [django-statsd/django-statsd#54]
django-statsd current statsd gauge signature 
(in log and toolbar clients)

``` python
def gauge(self, stat, value, rate=1):
```

like in statsd version 1.0.0 (this version also in requirements.txt)

but django-statsd-mozilla pypi package requires statsd>=2.0.0
there gauge signature was changed to

``` python
def gauge(self, stat, value, rate=1, delta=False):
```

**Comment by xordoquy** [comment]
Closing it as #55 was merged
