### ISSUE TITLE
debug toolbar panel content not showing, django 1.6 + debug-toolbar 1.2 + django-statsd 0.3.12

### ISSUE THREAD

**Issue by KevinBrolly** [django-statsd/django-statsd#60]
With the latest version of both debug-toolbar and django-statsd the debug-toolbar does not show the panel contents and instead outputs:

<bound method statsdpanel.content of <django_statsd.panel.statsdpanel object at 0x1157c9a90>></bound>

**Comment by xordoquy** [comment]
Closing this as I've dropped the support on Django 1.6
