### ISSUE TITLE
Incompatibilty with eventlet

### ISSUE THREAD

**Issue by nihn** [django-statsd/django-statsd#76]
Hi,

when django-statsd is used along with eventlet (0.15.1) package there is a Runtime Exception:

`RuntimeError("Second simultaneous write on fileno 5 detected.  Unless you really know what you're     doing, make sure that only one greenthread can write any particular socket.  Consider using a  pools.Pool. If you do know what you're doing and want to disable this error, call eventlet.debug.hub_prevent_multiple_readers(False) - MY THREAD=<built-in method switch of greenlet.greenlet object at 0x2e62910>; THAT THREAD=FdListener('write', 5, <built-in method switch of greenlet.greenlet object at 0x30de7d0>, <built-in method throw of greenlet.greenlet object at 0x30de7d0>)",)`

  File "statsd/client.py", line 88, in incr
    self._send_stat(stat, '%s|c' % count, rate)
  File "statsd/client.py", line 112, in _send_stat
    self._after(self._prepare(stat, value, rate))
  File "statsd/client.py", line 127, in _after
    self._send(data)
  File "statsd/client.py", line 132, in _send
    self._sock.sendto(data.encode('ascii'), self._addr)
  File "eventlet/greenio.py", line 370, in sendto
    self._trampoline(self.fd, write=True)
  File "eventlet/greenio.py", line 185, in _trampoline
    mark_as_closed=self._mark_as_closed)
  File "eventlet/hubs/__init__.py", line 157, in trampoline
    listener = hub.add(hub.WRITE, fileno, current.switch, current.throw, mark_as_closed)
  File "eventlet/hubs/epolls.py", line 48, in add
    listener = BaseHub.add(self, evtype, fileno, cb, tb, mac)
  File "eventlet/hubs/hub.py", line 169, in add
    evtype, fileno, evtype, cb, bucket[fileno]))

**Comment by Nihn** [comment]
Is there any chance to have this fixed any time soon?

**Comment by andymckay** [comment]
Best chance for fixing an interaction with another library like this is to send us a pull request.

**Comment by xordoquy** [comment]
Will consider a PR to fix it but closing this issue meanwhile as it's not something I'm going to work on myself.

**Comment by vinayinvicible** [comment]
This is happening because all of the eventlets/greenlets are trying to use the same socket.

@xordoquy
Have sent a PR to fix this issue.
