### ISSUE TITLE
Travis CI no longer running on new commits

### ISSUE THREAD

**Issue by blaze33** [django-statsd/django-statsd#91]
Seems like it's because the repo was changed from `andymckay/django-statsd` to `django-statsd/django-statsd`.

It would be nice to know if the new tests enabled by https://github.com/django-statsd/django-statsd/commit/bce92c61a2bdd5b4afa3ae1e1a5b75fdd6e858d5 are actually passing :)

**Comment by xordoquy** [comment]
Fixed.
