### ISSUE TITLE
Can you update the pypi for support Django 1.9 ?

### ISSUE THREAD

**Issue by joway** [django-statsd/django-statsd#97]
#93 #90 

 [django-statsd-mozilla](https://pypi.python.org/pypi/django-statsd-mozilla) now still stay at 2015-10-01	

Thanks for your helpful statsd tool !

**Comment by Duologic** [comment]
We've started our own fork here to keep up the pace with our internal development: 

https://pypi.python.org/pypi/django-statsd-unleashed

It should support new versions of Django and Python. Maybe this can be of any help to you too.

**Comment by xordoquy** [comment]
Timing seems to be pretty bad here.
@Duologic why didn't you asked for the maintainer ship instead of forking ?

**Comment by xordoquy** [comment]
Things are in a good enough shape for a release. All the build are now green, tests are running smooth and browser side clients are working

**Comment by Duologic** [comment]
I'm sorry, we've had pull requests open for quite some time without a response and didn't want to wait any longer. I'll happily make a new pull request.

Also, the docs state you've been looking for a new maintainer, that gave me the idea this project was halfway to being abandoned.

**Comment by Duologic** [comment]
I've been working on raising the test coverage too and running it on multiple Django and Python versions, check it out here: https://github.com/vikingco/django-statsd/pull/6

I'd love to work together getting it into upstream. However, I've made some decisions that might not fit the original project (ie. using py.test, dropping support for metlog-py, etc.). See this commit for a more complete list: https://github.com/vikingco/django-statsd/commit/b74b739521799e07e27c70b1b54136fe8f6cf9eb

**Comment by xordoquy** [comment]
@Duologic don't worry, it's my fault here.
I got the ownership like 2 days after you left the comment and I started to clean things up locally before looking at the issue list.
Just committed the work I started.
Would you be willing to join ?

**Comment by xordoquy** [comment]
> using py.test, dropping support for metlog-py

Like I've set up tox & py.test and considering dropping metlog-py as it's deprecated in favor of a deprecated project too.
Looks like we have a match ;)

**Comment by Duologic** [comment]
Alright, I'll make a pull request so you (and others) can add your comments on it for a merge.

**Comment by Duologic** [comment]
Let me first merge our branches into our master so we get a clear overview. I'll do that tomorrow when I'm at the office.

**Comment by xordoquy** [comment]
Had a quick look at you branch and looks like you did a nice job !

**Comment by xordoquy** [comment]
@Duologic mind if I pull your branch and start merging ?

**Comment by Duologic** [comment]
I was just looking at merging our changes into yours and came over this pattern:

```
import django_statsd.views
#do something with "django_statsd.views.record"
```

I'm rather a fan of doing this:

```
from .views import record
# do something with "record"
```

What do you think?

**Comment by xordoquy** [comment]
That's ok for me as well.

**Comment by Duologic** [comment]
I'm having some trouble with the complexity of the .travis.yml and I'm not really a fan of tox. So I made a branch that currently has a much simpler version of .travis.yml and runs pytest directly from Travis instead of via Tox.

Rebased on your changes: https://github.com/vikingco/django-statsd/pull/7

Is there a good reason to support pypy and pypy ? I'm not very well known with those python binaries. 

Feel free to leave some comments or suggestions.

**Comment by xordoquy** [comment]
I find tox is very useful for me to run the test matrix locally.
Whenever I want to skip all the overhead, I simply run `.tox/py34-django111/bin/py.test` and get done

**Comment by ownaginatious** [comment]
Wow, I was just about to ask if a new version could be posted to PyPI as well. Glad to see someone has taken control of this project and that the Django 1.11 issues have been ironed out 👍

Any idea on when the PyPI update will happen?

**Comment by xordoquy** [comment]
No ETA for now. I'd like to converge with @Duologic first.

**Comment by ownaginatious** [comment]
@Duologic @xordoquy are you both still working on converging?

**Comment by Duologic** [comment]
I hope to get to it somewhere next week. Shouldn't be too much work anymore. Sorry for the delay.

**Comment by ownaginatious** [comment]
Cool, thanks for the update :)

**Comment by ownaginatious** [comment]
Any updates here? :/

**Comment by xordoquy** [comment]
lots of personal things ongoing but will try to get this moving this week end.

**Comment by Duologic** [comment]
Same here, fairly busy. If you want, pull in any changes that you like. When I find more time, I'll make smaller pull request for each feature

**Comment by michael-k** [comment]
@xordoquy Any news?

**Comment by ownaginatious** [comment]
It's ironic how this repo was taken over due to no maintenance, only to immediately end up back in the same situation...

**Comment by xordoquy** [comment]
@ownaginatious thanks for your contribution !
@michael-k still revering from overload. Will try to get this fixed as soon as I can.

**Comment by ownaginatious** [comment]
@xordoquy sorry for the undeserved snarky comment. It just seems like everything's stalled on things unrelated to this actual issue here.

I think it's great that there are improvements coming in around style and automated testing/coverage, but I don't think it should be blocking updates for Django compatibility. I actually had a PR to submit to fix the 1.9+ compatibility issues, but got rid of it when I saw you'd coincidentally taken over maintainership and fixed most of the issues already.

If seems to me that if PR #104 were to merge into `master`, then at the very least, this library would work for Django 1.9, 1.10, 1.11 and (theoretically) 2.0.

Given that you and @Duologic seem very busy, that seems like the path of least resistance for getting a new PyPI version up.

**Comment by michael-k** [comment]
It already works with Django 1.11, we're using both on production (on Python 3.6).  We're just annoyed by the long list of deprecation warnings that our test runs produce.

**Comment by ownaginatious** [comment]
Whoops you're right; it's been a while and I got this confused with some of the other dependencies we submitted PRs to that did have breaking compatibility issues with Django 1.11.

We raise deprecation warnings to errors in our tests, so in the mean time we've been getting this dependency by commit hash from a fork of this repo in our builds where the deprecation warnings are fixed.

**Comment by xordoquy** [comment]
Version 0.4.0 uploaded on pypi.

**Comment by ownaginatious** [comment]
@xordoquy thanks, appreciate it :+1:
